export const RequirementProduct=[
	{
		Company:"FabGreen Technologies",
		Link:"https://www.fabgreentechnologies.com/",
		role:"React Js Developer",
		ctc:'150000',
		natureofjob:'Full-Time',
		opening:'1',
		deadline:'No Deadline',
		program:'Full Stack Development',
		
	},
	{
		Company:"ES Magico",
		Link:"https://www.esmagico.in/",        
		role:"Full Stack Developer",
		ctc:'150000',
		natureofjob:'Full-Time',
		opening:'1',
		deadline:'No Deadline',
		program:'Full Stack Development',
	},
	{
		Company:"Devtestingtesting",
		Link:"https://www.testdevlab.com/",        
		role:"Web Developer",
		ctc:'720000',
		natureofjob:'Full-Time',
		opening:'4',
		deadline:'No Deadline',
		program:'Full Stack Development',
	},
    {
		Company:"Dev test 23223",
		Link:"https://www.broadcom.com/info/continuous-testing/devtest-portfolio-overview",        
		role:"Web Developer",
		ctc:'720000',
		natureofjob:'Full-Time',
		opening:'5',
		deadline:'No Deadline',
		program:'Full Stack Development',
	},
    {
		Company:"Metricoid Technology Solutions",
		Link:"https://metricoidtech.com/",        
		role:"MERN Stack Developer",
		ctc:'300000',
		natureofjob:'Full-Time',
		opening:'4',
		deadline:'No Deadline',
		program:'Full Stack Development',
	},
    {
		Company:"EVeez",        
		Link:"https://www.eveez.in/eBikes-on-rent",        
		role:"MERN Stack Developer Intern",
		ctc:'300000',
		natureofjob:'Intern',
		opening:'2',
		deadline:'No Deadline',
		program:'Full Stack Development',
	},
    {
		Company:"Ayoo.care",        
		Link:"https://ayoo.care/",        
		role:"Backend Developer",
		ctc:'400000',
		natureofjob:'Full-time',
		opening:'1',
		deadline:'No Deadline',
		program:'Full Stack Development',
	},
    {
		Company:"Rapidqube",        
		Link:"https://www.rapidqube.com/about-us/",        
		role:"Software engineer trainee",
		ctc:'220000',
		natureofjob:'Full-time',
		opening:'15',
		deadline:'No Deadline',
		program:'Full Stack Development',
	},
    {
		Company:"Datalligence",        
		Link:"https://datalligence.ai/",        
		role:"Node JS Developer",
		ctc:'300000',
		natureofjob:'Full-time',
		opening:'1',
		deadline:'No Deadline',
		program:'Full Stack Development',
	},
    {
		Company:"Datalligence",        
		Link:"https://datalligence.ai/",        
		role:"React JS Developer",
		ctc:'300000',
		natureofjob:'Full-time',
		opening:'2',
		deadline:'No Deadline',
		program:'Full Stack Development',
	},
    {
		Company:"Finsights",        
		Link:"Finsights",        
		role:"React JS Developer",
		ctc:'400000',
		natureofjob:'Full-time',
		opening:'3',
		deadline:'No Deadline',
		program:'Full Stack Development',
	},
    {
		Company:"SIEORA",        
		Link:"https://www.sieora.in/",        
		role:"React JS Developer",
		ctc:'240000',
		natureofjob:'Full-time',
		opening:'2',
		deadline:'No Deadline',
		program:'Full Stack Development',
	},
    {
		Company:"Joy Technologies",        
		Link:"https://www.Joy Technologies.com/",        
		role:"Full Stack Developer",
		ctc:'350000',
		natureofjob:'Intern-Full-time',
		opening:'2',
		deadline:'No Deadline',
		program:'Full Stack Development',
	}
];